import { BrandMark } from '@/components/layout/BrandMark'
import { DOCUMENT } from '@/lib/document'

/**
 * The institutional footer, replacing ui.html:517-538.
 *
 * Every value here is either a property of the file on disk or a plain
 * statement of what the system does not do. Nothing is fetched.
 *
 * The mock's copy was fabricated and had to go rather than be restyled:
 *   - "Deterministic SEC retrieval engine" — not deterministic. The answer is
 *     generated by gemini-2.5-flash at temperature and re-ranked by Self-RAG.
 *   - "compliant with SOC-2 Type II and FINRA ... provenance rules" — no audit
 *     and no regulator are involved in this project at all.
 *   - "#edgar-sla" and "#cryptography" — anchors that exist nowhere, pointing at
 *     an SLA and a hash-verification spec that were never built.
 *   - "© 2025 Aureus Intelligence Labs" — a company that does not exist, in a
 *     stale year. The shipped brand is "Finance RAG"; see Navbar.
 *
 * Deliberately absent: any index or model statistics. Those already render in
 * the navbar, the hero and the chat panel, and a fourth bare "139" here would
 * collide with the unscoped getByText('139') assertion in hero.test.tsx.
 */
export function Footer() {
  return (
    <footer className="on-noir w-full bg-noir text-ivory py-14 border-t border-white/10 relative z-20">
      <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-6">
        <div className="group space-y-4 text-center md:text-left">
          <div className="flex items-center justify-center md:justify-start gap-3.5">
            <BrandMark />
            <div className="flex items-center gap-2">
              <span className="font-sans font-extrabold tracking-[0.2em] text-sm text-ivory">
                FINANCE RAG
              </span>
              {/*
                Whitespace as a sibling text node, not padding or a child. Flex
                `gap` is visual only: it never reaches textContent, so without
                this the wordmark reads as "FINANCE RAGSELF-RAG" when copied or
                announced. See the text-extraction note in AGENTS.md 7.
              */}
              {' '}
              <span className="text-[9px] px-1.5 py-0.5 rounded bg-gold/15 text-gold-dark font-mono font-medium tracking-tight">
                SELF-RAG
              </span>
            </div>
          </div>
          {/* `space-y-4` is margin, which is likewise absent from textContent. */}
          {' '}
          <p className="text-xs text-ivory/50 font-sans max-w-md leading-relaxed">
            Page-level retrieval over a single public SEC filing. Answers are
            model-generated and cite the page they came from, but they are not
            verified. Not financial advisory.
          </p>
        </div>
        {/* Sibling space, for the same textContent reason as the wordmark. */}
        {' '}
        {/*
          Labels, not links. There is no honest href to point at: the mock's
          two anchors led nowhere, and I have no verified URL for the filing
          itself, so inventing one would be the same mistake in a new place.
        */}
        <div className="flex flex-col sm:flex-row items-center gap-2 sm:gap-6 text-xs font-mono text-ivory/50">
          <span className="text-ivory/40">{DOCUMENT.filename}</span>{' '}
          <span aria-hidden className="hidden sm:inline text-white/20">
            &middot;
          </span>{' '}
          <span>&copy; {new Date().getFullYear()} Finance RAG</span>
        </div>
      </div>
    </footer>
  )
}
